name: Get active release branch
description: Search for the active release branch

outputs:
  active_release_branch:
    description: "Active Release Branch"
    value: ${{ steps.discover_active_release.outputs.active_release_branch }}

runs:
  using: "composite"
  steps:
    - name: Discover Active Release
      id: discover_active_release
      shell: bash
      run: |
        ACTIVE_RELEASE=$(git for-each-ref --sort=-committerdate --format '%(refname:strip=3)' refs/remotes/origin/release/* | head -n 1)
        echo "active_release_branch=$ACTIVE_RELEASE" >> "$GITHUB_OUTPUT"
    - name: Output Active release
      shell: bash
      run: echo "Active release ${{ steps.discover_active_release.outputs.active_release_branch }}"