name: Get active release branch
description: Search for the active release branch

outputs:
  active_release_branch:
    description: "Active Release Branch"
    value: ${{ steps.generate_new_tag.outputs.new_tag }}

runs:
  using: "composite"
  steps:
    - name: "Checkout source code"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Discover Active Release
      id: discover_active_release
      shell: bash
      run: |
        ACTIVE_RELEASE=$(git for-each-ref --sort=-committerdate --format '%(refname:short)' refs/heads/release/* | head -n 1)
        echo "Active release: $ACTIVE_RELEASE"
        echo "active_release_branch=$ACTIVE_RELEASE" >> $GITHUB_ENV
    - name: Output Active release
      shell: bash
      run: echo "Active release ${{ steps.discover_active_release.outputs.active_release_branch }}"