name: Deploy Release
on:
  push:
    tags:
      - 'v*'

run-name: "Deploy release TAG ${{ github.ref_name }}"

permissions:
  contents: write
  actions: write

jobs:
  deploy:
    name: Deploy release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Auto Deploy 1
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run release-auto-deploy.yaml \
            -f environment=default \
            -f team=my-team \
            -f tag=${{ github.ref_name }}
        continue-on-error: true