name: PR Status Check Validate Title
# run-name: "PR Status Check Validate Title - PR ${{ github.event.number }}"

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  pr-status-check-validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Validate PR Title
        id: validate-title
        uses: ./.github/actions/validate-title
        with:
          required-string: "TEAM"

      - name: Notify If Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const author = context.payload.pull_request.user.login;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `@${author},❌ Wrong PR Title, please include **TEAM** word in your PR Title.`
            });
