name: PR Status Check Build
# run-name: "PR Status Check Build - PR ${{ github.event.number }}"

on:
  workflow_run:
    workflows: [PR Status Check Validate Title]
    types:
      - completed

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  pr-status-check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build And Deploy
        if: ${{ github.event.workflow_run.conclusion == 'failed' }}
        id: build-deploy
        with:
          deploy-to-env: ${{ github.ref }}
        uses: ./.github/actions/build-deploy

      - name: Notify If Failure
        if: steps.build-deploy.conclusion == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const author = context.payload.pull_request.user.login;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `@${author},❌ Build/Deploy Failed, please check workflow logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            });
