name: PR Status Check Build
run-name: "PR Status Check Build - Branchs ${{ github.event.workflow_run.head_branch }}"

on:
  workflow_run:
    workflows:
      - PR Status Check Validate Title
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  pr-status-check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Build And Deploy
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        id: build-deploy
        with:
          deploy-to-env: ${{ github.ref }}
        uses: ./.github/actions/build-deploy

      - name: Notify If Failure
        if: steps.build-deploy.conclusion == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${github.event.workflow_run.head_branch}`
            }).then(response => response.data[0]?.number);

            const author = context.payload.actor;

            if (prNumber) {
              const workflowRunLink = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: `@${author},❌ Build/Deploy Failed, please check workflow logs at ${workflowRunLink}`
              });
            } else {
              console.log("PR not found for the branch");
            }
