name: Release - Auto Deploy
run-name: Release - Auto Deploy

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  actions: write

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix-team: ${{ steps.get_teams.outputs.teams }}
      active-release: ${{ steps.discover-release.outputs.active_release_branch }}
    steps:
      - name: "Fetch all code"
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Discover Active Release
        id: discover-release
        uses: ./.github/actions/discover-active-release

      - name: Get changed Teams since last run
        id: get_teams
        uses: ./.github/actions/get-teams-last-success-run
        with:
          workflow_name: "Release - Auto Deploy"
          save_json_to: 'build/teams.json'
          valid_teams: ${{ vars.VALID_TEAMS }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          repository_name: ${{ github.event.repository.name }}
          branch: ${{ steps.discover-release.outputs.active_release_branch }}

      - name: "Checkout to main"
        uses: actions/checkout@v4
        with:
          ref: main

  deploy:
    needs: discover
    runs-on: ubuntu-latest
    if: ${{ needs.discover.outputs.matrix-team != '[]' }}
    strategy:
      matrix:
        team: ${{ fromJson(needs.discover.outputs.matrix-team) }}
    steps:
      - name: "Fetch workflow code from main"
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1
      - name: Deploy ${{ matrix.team }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run deploy-team.yaml \
            --ref main \
            -f environment=default \
            -f team=${{ matrix.team }} \
            -f branch=${{ needs.discover.outputs.active-release }}
        continue-on-error: true